[package]
name = "vex-rt"
version = "0.7.0"
authors = [
    "Timothy Morland <me@timothy-morland.com>",
    "Nick Mertin <nickmertin@gmail.com>",
    "Jai Agrawal <jaiagr@pm.me>",
]
edition = "2018"
build = "build/main.rs"
description = "A Rust runtime for the Vex V5 built on top of PROS."
license = "MIT"
repository = "https://gitlab.com/qvex/vex-rt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2", default-features = false }
libc-print = "0.1.14"
rcstring = "0.2.1"
spin = "0.9.0"
newlib-alloc = "0.1.0"
cstring-interop = "0.1.0"
by_address = "1.0.4"
owner-monad = "0.1.0"
raii-map = "0.1.0"
queue-model = "0.1.2"

[build-dependencies]
bindgen = "0.58.0"
zip = "0.5.9"
zip-extensions = "0.6.0"

[dev-dependencies]
array-init = "2.0.0"
itertools = { version = "0.10.0", default-features = false, features = ["use_alloc"] }
